name: compress-images

on:
  push:
    branches: [master]
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
  workflow_dispatch:

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compress Images!
      uses: creyD/crush_action@v1.0
      with:
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
